### PR TITLE
Added the ability to register analyzers to Node\Scalar

### PR DESCRIPTION
**Pull request by nikhilsaldanha**
Hey!

Type: new feature

Link to issue: #221 

This pull request affects the following components **(please check boxes):**

* [ ] Core
* [x] Analyzer
* [x] Compiler
* [ ] Control Flow Graph
* [ ] Documentation

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/ovr/phpsa/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

created listener to Node\Scalar
created ScalarBeforeCompiler event
added registration function registerScalarPasses to Analyzer.php
registerScalarPasses call from Factory.php to register a Scalar analyzer

Thanks

### CODE REVIEW

**Comment by ddmler** [comment]
Travis failed when installing caching things, don't mind it.
Can you add the analyzer to this PR? Then we can see if all works correctly
You would also need to fire the event before compile.

**Comment by nikhilsaldanha** [comment]
Okay sure. Thanks!

**Comment by K-Phoen** [comment]
@nikhilsaldanha You should rebase this PR as I just merged some changes to the analyzers, it will make it easier for you when you'll start working on your new analyzer :)

**Comment by nikhilsaldanha** [comment]
@K-Phoen Okay, thanks :)

**Comment by nikhilsaldanha** [comment]
I've written a compiler and the analyzer for LNumber. I feel that I have missed out something because tests are failing. Do you know what it is?

**Comment by ddmler** [comment]
Your Scalar Compiler is never used.
https://github.com/ovr/phpsa/blob/master/src/Compiler/Expression.php#L305
currently the scalars are handled here. You would have to move all the scalars into your scalar compiler and add a call to your scalar compiler instead for all expr instanceof Node\Scalar.

Also your scalar compilers need to return a compiledExpression (the things you see in the link above) and not call the compile function.

**Pull request closed without merging**
