### PR TITLE
fix typo on line 50

### PR DESCRIPTION
**Pull request by chasingSublimity**
Hey!

Type: documentation

Link to issue: per comment on PR [#189](https://github.com/ovr/phpsa/pull/189)

This pull request affects the following components **(please check boxes):**

* [ ] Core
* [ ] Analyzer
* [ ] Compiler
* [ ] Control Flow Graph
* [x] Documentation

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/ovr/phpsa/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

Thanks

### CODE REVIEW

**Comment by K-Phoen** [comment]
You also need to update [the tests](https://github.com/ovr/phpsa/blob/a323dc1a7088727fa6e6ac285ee7317a3bfe2f95/tests/analyze-fixtures/Expression/Casts.php) :)

**Comment by chasingSublimity** [comment]
Gotcha. Sorry for the piecemeal PR's! I'm a better editor than developer at this point. :)

**Comment by ddmler** [comment]
@chasingSublimity you can also add commits to your patch branches or do you still need the 4 PR for hacktoberfest? :smile:

**Comment by chasingSublimity** [comment]
@ddmler Ha, I've satisfied the PR's for hacktoberfest, I'm just still learning the Github ropes. Background is in writing and editing, not coding. :)

**Comment by ddmler** [comment]
@chasingSublimity ok no problem. If you go to your repo and choose the branch patch-3 all commits there will land automatically here in this PR.
Here's the link: https://github.com/chasingSublimity/phpsa/tree/patch-3
just edit the test file there.

**Comment by chasingSublimity** [comment]
@ddmler That makes sense, thanks for the help!

**Comment by ddmler** [comment]
@chasingSublimity in casts analyzer (not test file) there is still a . in line 57 (unset cast)

**Comment by chasingSublimity** [comment]
fixed.

**Comment by ddmler** [comment]
Thanks @chasingSublimity 
If you are interested in coding and not just editing, we have some issues suitable for beginners: 159, 162, 163
they all contain step by step guides

**Comment by chasingSublimity** [comment]
Thanks for the heads up!

**Pull request merged**
