### PR TITLE
Statement Analyzer to check for Assignment in If,ElseIf Conditions

### PR DESCRIPTION
**Pull request by nikhilsaldanha**
Hey!

Type: new feature

Link to issue: #147 

This pull request affects the following components **(please check boxes):**

* [ ] Core
* [x] Analyzer
* [ ] Compiler
* [ ] Control Flow Graph
* [ ] Documentation

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/ovr/phpsa/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
Added a Statement Analyzer to check for Assignment conditions in if and elseif conditionals and wrote tests for the same.

Thanks

### CODE REVIEW

**Comment by ddmler** [comment]
@nikhilsaldanha 
You can find the Node Classes here: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/For_.php

As you can see For has the same `$cond` that you need to check.
Actually you don't need the private function checkAssignment. Copy that function into pass and delete all you have in pass right now.
Then you only need to register to the correct Stmt (not switch for example):
Case_
For_
If_
Elseif_
While_
Do_
Because those all have the `$cond` property so they get the same treatment. You don't need anything more than the check if cond is an assignment.

**Comment by nikhilsaldanha** [comment]
@ddmler Yes, I tried doing that initially. But, my tests were failing and indeed I tried it just now again with the same result.

By doing a few error logs inside pass, I realized that all the ElseIf_ objects are part of the elseifs array of the parent If_ and all Case_ objects are part of cases array of the Switch_ object. They are not passed as an Stmt_ to the pass function separately even if they are registered.

Therefore I had to iterate through them.

When I did the error logs, this is what pass and getRegister looked like:
```php
public function pass($stmt, Context $context)
{
    $result = false;
    // Error logging part. Excuse the dreadful code
    if ($stmt instanceof ElseIf_) {
        error_log("elseif");
    } elseif ($stmt instanceof Case_) {
        error_log("case");
    } elseif ($stmt instanceof If_) {
        error_log("if");
    } elseif ($stmt instanceof While_) {
        error_log("while");
    } elseif ($stmt instanceof Do_) {
        error_log("do");
    } elseif ($stmt instanceof Switch_) {
        error_log("switch");
    } else {
        error_log("for");
    }
    // this is the required part of pass
    if ($stmt->cond instanceof Assign) {
        $context->notice(
            'assignment_in_condition',
            'An assignment statement has been made instead of conditional statement',
            $stmt
        );
        $result = true;
    }
    return $result;
}

// I have registered all the statements
public function getRegister()
{
    return [
        If_::class,
        ElseIf_::class,
        While_::class,
        Case_::class,
        Do_::class,
        Switch_::class,
    ];
}
```

This was the output. As you can see, only if, while, do and switch statements are encountered by pass.
screen shot 2016-10-06 at 5 12 05 pm

Am I making some mistake?

**Comment by ddmler** [comment]
@nikhilsaldanha sorry my mistake. we fire no event for case and elseif right now. I will merge your PR and change it myself. Thanks for your work :+1:

**Comment by nikhilsaldanha** [comment]
@ddmler No problem. Happy to help

**Pull request merged**
