### PR TITLE
Detect old-style constructors

### LINKED ISSUE #103: Old style constructors
PHPSA should warn about old style class constructors.

``` php
class Foo {
    public function Foo() {
    }
}
```

### PR DESCRIPTION
**Pull request by K-Phoen**
Resolves #103

### CODE REVIEW

**Comment by ddmler** [comment]
@K-Phoen @ovr 
I think we should move all those checks out of definition into analyzers. So we don't have the checks all over the place. (right now in: analyzer, compiler, definition) What do you think?
check #105

**Comment by K-Phoen** [comment]
Ooops, I didn't see your PR, sorry :)

I agree with you though, we should stop doing checks directly in the definitions or compiling code. Analyzers should be doing this kind of work.

That being said, I think that the current analyzers are not enough to efficiently do all the checks needed.
Take your PR for instance: in the analyzer you have to iterate through all the class statements in order to detect if one of them has the right name. This work has already been done by the compiler and the analyzers should be able to benefit from the compilation step.

Concretely, this could be implementing by firing a new event `ExpressionAfterCompile` with the expression, the context and the result of the compilation.

**Comment by ddmler** [comment]
I had to loop through that because I had to use Class_ instead of ClassDefinition (it has to be a child of Node\Stmt I believe) and this class doesn't have those helper functions.

As for your new event: good idea but I think it won't help with old-style-constructor because we just need to change Class_ to ClassDefinition for it to work with the beforeCompile event. But we would have to get it working with the event listener so maybe making it a child of Node\Stmt?

**Comment by ovr** [comment]
@K-Phoen I am going to close this PR, because it's needed to work with on `Analyzer` and events
lets discuss on https://github.com/ovr/phpsa/pull/105

**Pull request closed without merging**
