### PR TITLE
Add analyzer for fixed value conditions

### LINKED ISSUE #218: [Analyzer] Fixed condition
Simple Task: We need an analyzer for this:
```php
if (condition) { // condition is always true, false
```

How To:
1. Statement Analyzer: register to the same as AssignmentInCondition analyzer.
Use `$context->getExpressionCompiler()->compile($stmt->cond);` to compile the condition down to value. Also check that if getType() is unknown we don't notice anything.
Write a nice notice message for it.
2. Add it to PHPSA\Analyzer\Factory (registerStatementPass)
3. Write test (analyze-fixtures directory): one without fixed condition and at least one with. (see existing tests on how to write this one)

Check our Contributing Guide and make a pull request.
Thanks :cake:

### PR DESCRIPTION
**Pull request by hanzi**
Hey!

Type: new feature

Link to issue: fix #218 

This pull request affects the following components **(please check boxes):**

* [ ] Core
* [x] Analyzer
* [ ] Compiler
* [ ] Control Flow Graph
* [ ] Documentation

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/ovr/phpsa/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Adds a new Analyzer that raises a notice if an `if`/`elseif`/`while`/`do`/`switch` condition has a predictable value.

Thanks

### CODE REVIEW

**Comment by ddmler** [comment]
Thanks @hanzi I forgot that Elseif_ is still a pull request. I will change that myself then.

**Comment by hanzi** [comment]
@ddmler I left that out on purpose since it does not seem to have any effect.

The `pass()` method never receives an `ElseIf_` instance even when it’s in the list of registered statements.

Instead, I had to check for `If_` and then manually iterate over its `elseifs` property (the same way it was done in `AssignmentInCondition`.)

So I decided to leave it out of the list for transparency’s sake. I originally didn’t see that iteration in `AssignmentInCondition` and it took me some time to figure out why `elseif` didn’t work.

**Comment by ddmler** [comment]
@hanzi Yes ElseIf_ does not fire an event at the moment. PR #194 fixes that (I changed your analyzer there already)

**Comment by ovr** [comment]
@hanzi @ddmler 

Can anyone me explain why it's need?

I cannot write code like

```
while (true) {
    break;
}
```

rly?

**Pull request merged**
