### PR TITLE
Make asserts consistent

### PR DESCRIPTION
**Pull request by ddmler**
Hey!

Type: code quality

Link to issue:

This pull request affects the following components **(please check boxes):**

* [ ] Core
* [ ] Analyzer
* [ ] Compiler
* [ ] Control Flow Graph
* [ ] Documentation

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/ovr/phpsa/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

https://github.com/sebastianbergmann/phpunit/issues/1914#issuecomment-148407321

this should be used instead of a static call.

### CODE REVIEW

**Comment by ovr** [comment]
All this methods are `static`

image

https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Framework/Assert.php#L16

We should use `parent::`

**Comment by ddmler** [comment]
@ovr see my link above for reasons to use this instead.
Official phpunit docs use this too, so we should go with the commonly used way.
parent offers no benefit for us.

**Comment by ovr** [comment]
@ddmler Asked some guys about `$this->` instead of `parent::` in Twitter
IMHO I think We should use `parent::`

**Comment by ovr** [comment]
image

**Comment by ddmler** [comment]
will create a new PR so closing this

**Pull request closed without merging**
