### PR TITLE
Unexpected use of this

### PR DESCRIPTION
**Pull request by K-Phoen**
I started to work on an implementation of unexpected uses of `$this` (#68).

Most of the easy cases are covered and I'd like your feedback on this PR as I'm not familiar with this project (yet). Am I going in the right direction? If yes, I'll try to detect more error cases and add a few unit tests.

### CODE REVIEW

**Comment by ddmler** [comment]
Looks good. i think what's left to do is:
- function parameter (same as method but it's a different node called "Function_")
- setting $this with extract(), parse_str(), list(), possibly other functions?

i'm not quite sure what the purpose of the fixtures directory is @ovr ?

**Comment by ovr** [comment]
@K-Phoen Rly cool work bro 👍 
I will try to review your PRs today in the evening

@ddmler 
> i'm not quite sure what the purpose of the fixtures directory is @ovr ?

For now I think We need to put it in `tests/analyze-fixtures` in file named as `Analyzer` name
In the feature will be cool to split it but I dont known how

**Comment by K-Phoen** [comment]
> function parameter (same as method but it's a different node called "Function_")

Yep, will do :)

> setting $this with extract(), parse_str(), list(), possibly other functions?

I'm not sure about these cases. At least for `extract()` and `parse_str()`, their input usually is really dynamic and implementing a check for them might not be worth the trouble. WDYT?
Checking for `$this` usage in `list()` calls should be easy though.

**Comment by ovr** [comment]
I am going to close and open PR to restart CI

**Comment by ovr** [comment]
Branch should be rebased

image


```
git fetch origin
git rebase origin/dev
```

On conflicts

```
git add .
git rebase --continue
```

After rebase git push YOUREMOVE unexpected-use-of-this -f

Thanks

**Comment by K-Phoen** [comment]
Rebased :)

**Comment by ovr** [comment]
PR LGTM, Thank you, rly cool Analyzer 👍 Appreciate you work on it

Related to @ddmler comment
> - function parameter (same as method but it's a different node called "Function_")
- setting $this with extract(), parse_str(), list(), possibly other functions?

Will rly to have this too, you can do it it another PR 😸

**Pull request merged**
