### PR TITLE
Add analyzer for stupid unary operator

### LINKED ISSUE #204: [Analyzer] Stupid unary operator
UnaryPlus + positive number

```php
$a = +1;
$a = +1.0;
$a = +true;
```

think about: maybe change multiple unary analyzer to be a stupid unary analyzer and put both together or make a new analyzer.

### PR DESCRIPTION
**Pull request by Lexty**
Hey!

Type: new feature

Link to issue: fix #204 

This pull request affects the following components **(please check boxes):**

* [ ] Core
* [x] Analyzer
* [ ] Compiler
* [ ] Control Flow Graph
* [ ] Documentation

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/ovr/phpsa/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
Adds a new Analyzer that raises a notice for a single plus unary operator.

Thanks

### CODE REVIEW

**Comment by ddmler** [comment]
Hi @Lexty 
Thanks for PR but:
`++$a;` is not double unary plus operator but another operator called PreInc. (adds 1 to value)
`+$a;` is the identity function. (not abs() function like i thought) So probably the only reason to use this would be to cast something to int or float.

We should change the analyzer just to always give a notice message when using UnaryPlus that it is better to use an int or float cast.

**Comment by Lexty** [comment]
Hi @ddmler! Thanks for response.
As I understand, tests are correct and we should just change the message, right?
How about `Better to use type casting then unary plus.`?
I have updated the commit.

**Comment by ddmler** [comment]
@Lexty we merged Configuration, can you rebase this branch and add the trait to your analyzer (see all other traits)

**Comment by ddmler** [comment]
Thanks @Lexty :cake:

**Pull request merged**
